### ISSUE TITLE
iOS build broken

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#782]
This sort of thing will be caught more easily once I hit https://github.com/mapbox/mapbox-gl-cocoa/issues/28 so that iOS build bugs are caught upon commit. 

```
In file included from /tmp/gl/src/mbgl/map/tile_parser.cpp:15:
In file included from src/mbgl/text/collision.hpp:16:
In file included from /usr/local/include/boost/geometry.hpp:17:
In file included from /usr/local/include/boost/geometry/geometry.hpp:43:
In file included from /usr/local/include/boost/geometry/strategies/strategies.hpp:74:
In file included from /usr/local/include/boost/geometry/strategies/agnostic/relate.hpp:14:
In file included from /usr/local/include/boost/geometry/algorithms/detail/relate/relate.hpp:53:
/usr/local/include/boost/geometry/algorithms/detail/relate/linear_areal.hpp:300:81: error: implicit conversion loses integer precision: 'long' to 'const int' [-Werror,-Wshorten-64-to-32]
                        int const next_ring_index = prev_seg_id_ptr->ring_index + 1;
                                  ~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/usr/local/include/boost/geometry/algorithms/detail/relate/linear_areal.hpp:371:73: error: implicit conversion loses integer precision: 'long' to 'const int' [-Werror,-Wshorten-64-to-32]
                int const next_ring_index = prev_seg_id_ptr->ring_index + 1;
                          ~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from /tmp/gl/src/mbgl/map/tile_parser.cpp:15:
In file included from src/mbgl/text/collision.hpp:16:
In file included from /usr/local/include/boost/geometry.hpp:17:
In file included from /usr/local/include/boost/geometry/geometry.hpp:48:
In file included from /usr/local/include/boost/geometry/algorithms/buffer.hpp:32:
In file included from /usr/local/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:27:
In file included from /usr/local/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:42:
In file included from /usr/local/include/boost/geometry/algorithms/detail/occupation_info.hpp:21:
/usr/local/include/boost/geometry/algorithms/detail/get_left_turns.hpp:249:43: error: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]
            previous_index = cluster_size - 1;
                           ~ ~~~~~~~~~~~~~^~~
3 errors generated.
```

**Comment by incanus** [comment]
Still seeing this, and can't figure out with `git bisect` when it started. It appears to me to be a problem of treating as fatal a couple warnings in Boost around implicit integer conversion. 

@springmeyer @ljbade Any ideas here related to recent Mason changes / Boost pinning to support Android?

**Comment by incanus** [comment]
Here we go. The problem is in `core` and only on 64-bit, because of this being set to `YES`: 

    GCC_WARN_64_TO_32_BIT_CONVERSION

If I compile for iPhone 4s simulator (32-bit), there are no problems. So Boost is causing us grief on 64-bit iOS.

**Comment by incanus** [comment]
Came about because of the introduction of `-Werror` (treat warnings as errors) by @kkaefer in https://github.com/mapbox/mapbox-gl-native/commit/618a4a5785e07b9663111d8d7f4b33c0f6be0c55.

**Comment by jfirebaugh** [comment]
33f611cdf8d22aacdb252dee7f262a644af10882 is our standard solution for cases like this.

**Comment by jfirebaugh** [comment]
(The `#pragma`s around boost includes that is.)

**Comment by incanus** [comment]
Oh, perfecto — thanks @jfirebaugh; will implement.
