### ISSUE TITLE
-[MGLGeoJSONSource mbgl_source] mapbox::geojson symbol(s) not found

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#6194]
**Platform:** iOS
**Mapbox SDK version:** v3.4.0-alpha.2 (static)

Attempting to use the static framework with v3.4.0-alpha.2 results in several undefined symbols errors.

Both `arm64` and `x86_64` architectures are reported as missing.

```
Undefined symbols for architecture arm64:
  "mapbox::geojson::convert(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::CrtAllocator> const&)", referenced from:
      mbgl::style::conversion::Result<mapbox::util::variant<mapbox::geometry::geometry<double>, mapbox::geometry::feature<double>, mapbox::geometry::feature_collection<double, std::__1::vector> > > mbgl::style::conversion::convertGeoJSON<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::CrtAllocator> >(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::CrtAllocator> const&) in Mapbox(geojson_source_impl.o)
  "mapbox::geojson::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      -[MGLGeoJSONSource mbgl_source] in Mapbox(MGLGeoJSONSource.o)
ld: symbol(s) not found for architecture arm64
```

/cc @1ec5 @boundsj @kkaefer @mourner

**Comment by 1ec5** [comment]
Perhaps something changed during the CMake migration that keeps us from linking the static library to geojson-vt-cpp.

**Comment by friedbunny** [comment]
This appears to no longer be a problem — the static framework for v3.4.0-alpha.5 works as expected, as does one freshly compiled from master/alpha.6. Weird.
