### PR TITLE
Convert iOS SDK into dynamic framework

### LINKED ISSUE #828: dynamically-linked builds for iOS
Carryover from https://github.com/mapbox/mapbox-gl-native/pull/824. We build statically, but we want a `MapboxGL.framework` again. 

 * Ease of installation
 * Swift support
 * CocoaPods simplification

### LINKED ISSUE #3161: explore framework install for iOS
We have a framework script as of https://github.com/mapbox/mapbox-gl-native/commit/01b4f160d40b5899ed455e02bd673deca96b3a36. If we were to modify our CocoaPods spec to allow install from this framework, could we: 

1. Provide symbolicated/stripped `Mapbox.framework` zips instead of our current static library zips? 
1. Avoid use of `use_frameworks!` in users' `Podfile` because we already have a namespaced framework? 
1. Make drag and drop install with auto-linking of dependencies more of a reality? 

@1ec5 @friedbunny

### PR DESCRIPTION
**Pull request by 1ec5**
`make iproj` now produces a target that pulls together static libraries like core and platform-ios into a true dynamic framework (as opposed to a static library executable stuffed inside a framework bundle). iosapp is pretty much just a regular iOS application that links Mapbox.framework (except for the inclusion of default_styles.hpp).

~~For now, I’ve patched support for code signing files in Copy Files build phases into the ancient checked-in copy of gyp, pending #3178.~~

Dynamic framework distribution relies on a shell script copied from realm/realm-cocoa#2759. This script works around an [App Store bug](http://www.openradar.me/radar?id=6409498411401216).

Fixes #828, fixes #3161, paving the way for #1623. Based on #3135 for OS X.

/cc @incanus @friedbunny

### CODE REVIEW

**Comment by 1ec5** [comment]
Current progress on `make ipackage`:

```
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
```

**Comment by 1ec5** [comment]
Um, OK, so apparently the fix is to pass `-showBuildSettings` to `xcodebuild`. Huh?

**Comment by 1ec5** [comment]
One downside to shipping a true dynamic framework (as opposed to a framework bundle containing a static library, as we do now) is that App Store submissions [aren’t allowed to contain simulator content](http://www.openradar.me/radar?id=6409498411401216), as reported in Carthage/Carthage#188. If we ship a fat framework containing both device and simulator content, developers will need to strip the irrelevant content before code-signing. (Currently I’m relying on the “code sign on copy” build phase option that gets enabled when you use the Embedded Binaries section in the project editor.)

**Comment by 1ec5** [comment]
Currently, `make ipackage` produces a fat framework (with both device and simulator content) that weighs in at 62 MB. We’ll have to add instructions for stripping simulator content before submitting to the App Store, like [Realm’s](https://realm.io/docs/objc/latest/), to get around [this Xcode bug](http://www.openradar.me/radar?id=6409498411401216).

**Comment by tkrajacic** [comment]
Making the framework compatible with Carthage should now be possible which is awesome!

- The Xcode scheme that builds the framework needs to be shared for that purpose
- Better yet, the framework can be prebuilt

See https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by 1ec5** [comment]
package.sh now produces a pkg/ folder containing:

* a dynamically-linked, Bitcode-enabled framework in dynamic/
* a statically-linked, Bitcode-disabled framework in static/
* an example Settings.bundle
* API documentation in documentation/

To minimize our build and test matrix, I’ve omitted options for building a Bitcode-enabled static framework (for deploying back to iOS 7 in Xcode 7) or a Bitcode-disabled dynamic framework (for deploying to iOS 8.x only in Xcode 6.x).

**Comment by 1ec5** [comment]
@friedbunny @incanus @bsudekum (and anyone else interested), I’d like your help with this test plan, in order of priority:

* [ ] CocoaPods (latest version only)
 * [ ] Dynamic framework
 * [ ] Static library with `use_frameworks!` (for iOS 7 or Bitcode-less application)
* [ ] Fabric – dynamic framework only
* [ ] Manual drag-and-drop into Xcode
 * [ ] Dynamic framework
 * [ ] Verify that the [framework-stripping script](https://github.com/mapbox/mapbox-gl-native/blob/1ec5-ios-framework-828/docs/BUILD_IOS_OSX.md) plays nicely with Carthage-installed frameworks (which use a similar stripping mechanism) when exporting
 * [ ] Static library (for iOS 7 or Bitcode-less application)
* [ ] react-native-mapbox-gl
 * @bsudekum, this would be a good time for RNMBGL to drop support for iOS 7 so that you only have to distribute a dynamic framework via npm. You’ll need to update the Xcode project to refer to the .framework and remove references to the .bundle and headers from the project and [this script](https://github.com/mapbox/react-native-mapbox-gl/blob/master/scripts/download-mapbox-gl-native-ios.sh).

Testing one of the workflows above generally involves answering the following questions:

* Do each of the following scenarios build without warnings or errors in both Xcode 6.4 and Xcode 7.2?
 * application written in Objective-C or Swift
 * MGLMapView initialized in a storyboard or programmatically
* Does the application run both in the Simulator and on a device?
 * For this PR, it probably isn’t particularly important to test on a wide array of devices; just verify that it works on at least one device.
* Do assets like the Mapbox logo and default marker image appear?

Let me know if you have any questions about how to test one of these cases.

**Comment by friedbunny** [comment]
Going to start running through this list today, starting with CocoaPods.

**Comment by friedbunny** [comment]
Ran in to #3300, but the [`post_install` fix there](https://github.com/mapbox/mapbox-gl-native/issues/3300#issuecomment-166406984) works.

**Comment by friedbunny** [comment]
With CocoaPods and a direct install, IBDesignables dies with:

> No target found containing the source files defining `MGLMapView`. The class was found in `MGLMapView+IBAdditions.h, `MGLMapView.+MGLCustomStyleLayerAdditions.h`, and `MGLMapView.h`. Make sure at least one of these files are in the target.

screen-shot-2015-12-21-at-5 00 44-pm

**Comment by friedbunny** [comment]
CocoaPods + dynamic framework ticks all the boxes, with the `post_install` fix and except for the IBDesignables error.

**Comment by 1ec5** [comment]
Ah, yes, Interface Builder doesn’t support designables for binary-only frameworks (whether static or dynamic). It only works if the framework is a build product of a project in the workspace that contains source code. We could hack around this limitation by using the CocoaPods podspec to insert a source file that implements `-[MGLMapView(IBDesignableAdditions) prepareForInterfaceBuilder]` inside the application target.

I’m coming around to the idea of abandoning the designable. It’s much less important than the inspectables (which do work). The designable is unable to display an actual preview of the map because the Mapbox Style API uses SSL certificates, which means Cocoa Touch is unable to synchronously load any resources. The designable instead shows a setup checklist, but #3160 would be a much better way to streamline the setup process.

**Comment by 1ec5** [comment]
The manual static framework workflow is broken due to #3366:

```
duplicate symbol __ZN6mapbox9geojsonvt7Convert11projectRingERKNSt3__16vectorINS0_6LonLatENS2_9allocatorIS4_EEEEd in:
    /Users/mxn/Documents/Playroom/Sedan/Mapbox.framework/Mapbox(convert.o)
duplicate symbol __ZN6mapbox9geojsonvt7Convert12projectPointERKNS0_6LonLatE in:
    /Users/mxn/Documents/Playroom/Sedan/Mapbox.framework/Mapbox(convert.o)
duplicate symbol __ZN6mapbox9geojsonvt7Convert8calcSizeERNS0_13ProjectedRingE in:
    /Users/mxn/Documents/Playroom/Sedan/Mapbox.framework/Mapbox(convert.o)
duplicate symbol __ZN6mapbox9geojsonvt7Convert8calcBBoxERNS0_16ProjectedFeatureE in:
    /Users/mxn/Documents/Playroom/Sedan/Mapbox.framework/Mapbox(convert.o)
duplicate symbol __ZN6mapbox9geojsonvt7Convert12calcRingBBoxERNS0_14ProjectedPointES3_RKNSt3__16vectorIS2_NS4_9allocatorIS2_EEEE in:
    /Users/mxn/Documents/Playroom/Sedan/Mapbox.framework/Mapbox(convert.o)
duplicate symbol __ZN6mapbox9geojsonvt7Convert6createENSt3__13mapINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEES9_NS2_4lessIS9_EENS7_INS2_4pairIKS9_S9_EEEEEENS0_20ProjectedFeatureTypeENS_4util7variantIJNS2_6vectorINS0_14ProjectedPointENS7_ISL_EEEENSK_INS0_13ProjectedRingENS7_ISO_EEEEEEE in:
    /Users/mxn/Documents/Playroom/Sedan/Mapbox.framework/Mapbox(convert.o)
ld: 6 duplicate symbols for architecture i386
```

**Comment by 1ec5** [comment]
I guess this isn’t technically blocked by #3366, because at least it introduces a dynamic framework that works in Xcode 7.2, even if the static framework remains broken.

**Comment by 1ec5** [comment]
Turns out I hadn’t sufficiently cleaned my checkout. So the static framework isn’t broken after all.

**Comment by 1ec5** [comment]
I was [sure](https://github.com/mapbox/mapbox-gl-native/issues/3366#issuecomment-166807391) the drag-and-drop static framework case worked, but now trying a super-clean build in a new project, I’m seeing that codesigning verification fails on the device, causing the application to fail to install. Happens with both 03029d3115ee9ef008bc757957df41f6e6a57097 and 1716b699baa346ad434ef7f6bbf7a278a23f24a2. @friedbunny, are you seeing the same thing?

**Comment by friedbunny** [comment]
**Drag-and-drop static framework** is failing with undefined symbols when building for simulator with Xcode 7.3b1:

```objc
Ld /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphonesimulator/manualframework.app/manualframework normal x86_64
    cd /Users/jason/Desktop/manualframework
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode 7.3b1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode 7.3b1.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode\ 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode\ 7.3b1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphonesimulator -F/Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphonesimulator -F/Users/jason/Desktop/manualframework -filelist /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Intermediates/manualframework.build/Debug-iphonesimulator/manualframework.build/Objects-normal/x86_64/manualframework.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.0 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework Mapbox -Xlinker -dependency_info -Xlinker /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Intermediates/manualframework.build/Debug-iphonesimulator/manualframework.build/Objects-normal/x86_64/manualframework_dependency_info.dat -o /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphonesimulator/manualframework.app/manualframework

Undefined symbols for architecture x86_64:
  "_CGImageDestinationAddImage", referenced from:
      mbgl::encodePNG(mbgl::Image<(mbgl::ImageAlphaMode)1> const&) in Mapbox(image.o)
  "_CGImageDestinationCreateWithData", referenced from:
      mbgl::encodePNG(mbgl::Image<(mbgl::ImageAlphaMode)1> const&) in Mapbox(image.o)
  "_CGImageDestinationFinalize", referenced from:
      mbgl::encodePNG(mbgl::Image<(mbgl::ImageAlphaMode)1> const&) in Mapbox(image.o)
  "_CGImageSourceCreateImageAtIndex", referenced from:
      mbgl::decodeImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Mapbox(image.o)
  "_CGImageSourceCreateWithData", referenced from:
      mbgl::decodeImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Mapbox(image.o)
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in Mapbox(MGLMapView.o)
  "_kUTTypePNG", referenced from:
      mbgl::encodePNG(mbgl::Image<(mbgl::ImageAlphaMode)1> const&) in Mapbox(image.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And slightly differently when building for device:

```objc
Ld /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos/manualframework.app/manualframework normal armv7
    cd /Users/jason/Desktop/manualframework
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode 7.3b1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode 7.3b1.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode\ 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode\ 7.3b1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos -F/Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos -F/Users/jason/Desktop/manualframework -filelist /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Intermediates/manualframework.build/Debug-iphoneos/manualframework.build/Objects-normal/armv7/manualframework.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=7.0 -dead_strip -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -framework Mapbox -Xlinker -dependency_info -Xlinker /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Intermediates/manualframework.build/Debug-iphoneos/manualframework.build/Objects-normal/armv7/manualframework_dependency_info.dat -o /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos/manualframework.app/manualframework

Undefined symbols for architecture armv7:
  "_CGImageSourceCreateWithData", referenced from:
      mbgl::decodeImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Mapbox(image.o)
  "_CGImageSourceCreateImageAtIndex", referenced from:
      mbgl::decodeImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Mapbox(image.o)
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in Mapbox(MGLMapView.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Xcode 7.2 building for device fails but throws in different missing symbols:

```objc
Ld /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos/manualframework.app/manualframework normal armv7
    cd /Users/jason/Desktop/manualframework
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos -F/Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos -F/Users/jason/Desktop/manualframework -filelist /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Intermediates/manualframework.build/Debug-iphoneos/manualframework.build/Objects-normal/armv7/manualframework.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=7.0 -dead_strip -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -framework Mapbox -Xlinker -dependency_info -Xlinker /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Intermediates/manualframework.build/Debug-iphoneos/manualframework.build/Objects-normal/armv7/manualframework_dependency_info.dat -o /Users/jason/Library/Developer/Xcode/DerivedData/manualframework-dfmaduoutqxutlcfcetrbpckdway/Build/Products/Debug-iphoneos/manualframework.app/manualframework

Undefined symbols for architecture armv7:
  "_CGImageSourceCreateWithData", referenced from:
      mbgl::decodeImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Mapbox(image.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[MGLReachability isReachable] in Mapbox(reachability.o)
      -[MGLReachability isReachableViaWWAN] in Mapbox(reachability.o)
      -[MGLReachability isReachableViaWiFi] in Mapbox(reachability.o)
      -[MGLReachability connectionRequired] in Mapbox(reachability.o)
      -[MGLReachability isConnectionOnDemand] in Mapbox(reachability.o)
      -[MGLReachability isInterventionRequired] in Mapbox(reachability.o)
      -[MGLReachability reachabilityFlags] in Mapbox(reachability.o)
      ...
  "_SCNetworkReachabilitySetDispatchQueue", referenced from:
      -[MGLReachability startNotifier] in Mapbox(reachability.o)
      -[MGLReachability stopNotifier] in Mapbox(reachability.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[MGLReachability startNotifier] in Mapbox(reachability.o)
      -[MGLReachability stopNotifier] in Mapbox(reachability.o)
  "_CGImageSourceCreateImageAtIndex", referenced from:
      mbgl::decodeImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Mapbox(image.o)
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[MGLReachability reachabilityWithAddress:] in Mapbox(reachability.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[MGLReachability reachabilityWithHostname:] in Mapbox(reachability.o)
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in Mapbox(MGLMapView.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 1ec5** [comment]
You still need to [link lots of frameworks manually](https://www.mapbox.com/ios-sdk/#binary) when using the static framework. In this case, it looks like you’re missing ImageIO.framework.

**Comment by friedbunny** [comment]
Hrm, there may be something wrong with my build environs, the dynamic framework is dying, too:

```
dyld: Library not loaded: @rpath/Mapbox.framework/Mapbox
  Referenced from: /var/mobile/Containers/Bundle/Application/BA6B1E59-2A34-4F6F-8BD9-09997AD8226D/manualframework.app/manualframework
  Reason: image not found
(lldb) bt
* thread #1: tid = 0x16ba9e, 0x1fe4408c dyld`dyld_fatal_error, stop reason = EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xe7ffdefe)
  * frame #0: 0x1fe4408c dyld`dyld_fatal_error
    frame #1: 0x1fe4699a dyld`dyld::halt(char const*) + 74
    frame #2: 0x1fe48eaa dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 4298
    frame #3: 0x1fe441ee dyld`dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 342
    frame #4: 0x1fe44040 dyld`_dyld_start + 64
```

**Comment by friedbunny** [comment]
> You still need to link lots of frameworks manually when using the static framework. In this case, it looks like you’re missing ImageIO.framework and SystemConfiguration.framework.

Boo.

**Comment by friedbunny** [comment]
Carthage project (Swift, Xcode 7.3b1, rebuilt from Bitcode, adhoc distribution) with the stripping script failed:

```
failed to compile bitcode for mbglcarthage:
Debug: SDK path: /Applications/Xcode 7.3b1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk
Debug: PATH: ['/Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin', '/Applications/Xcode 7.3b1.app/Contents/Developer/usr/bin']
Debug: Using: /Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
MachoInfo: cd /
"/Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo" "-info" "/var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/ipatool20160112-66224-mgzma4/MachOs/iphoneos/armv7/com.mapbox.mbglcarthage/mbglcarthage" 
-= Output =-
Non-fat file: /var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/ipatool20160112-66224-mgzma4/MachOs/iphoneos/armv7/com.mapbox.mbglcarthage/mbglcarthage is architecture: armv7
Exited with 0

Debug: Command took 0 seconds
Debug: Using: /Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump
GetUUID: cd /
"/Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump" "-u" "/var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/ipatool20160112-66224-mgzma4/MachOs/iphoneos/armv7/com.mapbox.mbglcarthage/mbglcarthage" 
-= Output =-
UUID: F39ECD72-FBA8-3F4A-B913-D79C3F9BDB89 (armv7) /var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/ipatool20160112-66224-mgzma4/MachOs/iphoneos/armv7/com.mapbox.mbglcarthage/mbglcarthage
Exited with 0

Debug: Command took 0 seconds
Debug: Using: /Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/segedit
ExtractXAR: cd /
"/Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/segedit" "/var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/ipatool20160112-66224-mgzma4/MachOs/iphoneos/armv7/com.mapbox.mbglcarthage/mbglcarthage" "-extract" "__LLVM" "__bundle" "/var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/mbglcarthageSeZY3g/mbglcarthage.armv7.xar" 
-= Output =-
Exited with 0

Debug: Command took 0 seconds
Debug: Bitcode bundle version: 1.0
Debug: Setting platform to: iPhoneOS
Debug: Using: /Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
Debug: Using: /Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc
error: Swift: cd /var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/tempijhFUU
"/Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc" "-frontend" "-emit-object" "-target" "armv7-apple-ios8.0" "-O" "-module-name" "mbglcarthage" "-disable-llvm-optzns" "1.bc" "-o" "1.o" 
-= Output =-
error: Invalid type for value
Exited with 1


error: Failed to compile bundle: /var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/mbglcarthageSeZY3g/mbglcarthage.armv7.xar

error: Swift: cd /var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/tempijhFUU
"/Applications/Xcode 7.3b1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc" "-frontend" "-emit-object" "-target" "armv7-apple-ios8.0" "-O" "-module-name" "mbglcarthage" "-disable-llvm-optzns" "2.bc" "-o" "2.o" 
-= Output =-
<unknown>:0: error: error opening input file '2.bc' (No such file or directory)
Exited with 1


error: Failed to compile bundle: /var/folders/s5/2p4466vn2cv5mslx9ydthw6m0000gn/T/mbglcarthageSeZY3g/mbglcarthage.armv7.xar
```

**Comment by friedbunny** [comment]
Meanwhile, a Carthage-less dynamic framework project adhoc exported with `strip-frameworks.sh` and installed on device successfully.

**Comment by friedbunny** [comment]
Putting this down for today. The manual import scenarios are looking good, except for the Carthage export conflict (which I think can be avoided by using our new dynamic framework via Carthage and riding on their stripping mechanism).

Still need to test:
- Cocoapods + static framework
- Fabric

**Comment by 1ec5** [comment]
The stripping script won’t be part of the installation instructions for Carthage, so I think that failure is fine.

**Comment by 1ec5** [comment]
Regarding https://github.com/mapbox/mapbox-gl-native/pull/3183#issuecomment-169270434, it turns out to be an issue with the official 3.0.1 release as well: #3656. I’ve got a fix in hand.

**Comment by 1ec5** [comment]
e4d36be1dd93a1858df335ca2825f84a55e36c71 fixes #3656 and cleans up versioning with help from [this wonderful guide](http://blog.pioneeringsoftware.co.uk/2011/12/20/apple-generic-versioning/).

**Comment by chriszhang4213** [comment]
@1ec5 "The SDK is now distributed as a dynamic framework instead of a static library, resulting in a simpler installation workflow and significantly reduced download size. The framework contains both simulator and device content; due to an Xcode bug, you’ll need to strip out the simulator content before submitting your application to the App Store."

are you guys fix this? or we have to strip out the simulator content for 3.10 framework when submit to app store?

any guide for this?

**Comment by 1ec5** [comment]
@chriszhang4213, if you follow the installation instructions in the README.md that’s in the ZIP file you download, you’ll be just fine. The last step automatically strips the simulator content for you. Sorry for not making that clear.

**Comment by chriszhang4213** [comment]
@1ec5, you mean  
"1. In the Build Phases tab, click the + button at the top and select â€œNew Run Script please. Enter the following code into the script text field:

```bash
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"
```
"

this step right?

**Comment by 1ec5** [comment]
Yes, that step will strip out any framework content that doesn’t match the architecture you’re building for. So when you export for the App Store, the script will strip out any simulator content.

**Comment by 1ec5** [comment]
By the way, if you install using CocoaPods and the `use_frameworks!` flag, you don’t have to worry about this step at all.
