### ISSUE TITLE
[android] Flappy android-gnustl-arm-v7 tests

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#13987]
On `master` as of d34f0f0ef126ab794990a306a7a682daa1dbb3c8, `android-gnustl-arm-v7` [is flapping](https://circleci.com/gh/mapbox/mapbox-gl-native/235149), like so:

```
com.mapbox.mapboxsdk.maps.AnnotationManagerTest > checksAddAMarker FAILED
    java.lang.ExceptionInInitializerError
        at sun.reflect.GeneratedSerializationConstructorAccessor43.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
        at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
        at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:19)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:185)
        at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:69)
        at org.mockito.Mockito.mock(Mockito.java:1896)
        at org.mockito.Mockito.mock(Mockito.java:1805)
        at com.mapbox.mapboxsdk.maps.AnnotationManagerTest.checksAddAMarker(AnnotationManagerTest.java:26)

        Caused by:
        java.lang.NullPointerException
            at com.getkeepsafe.relinker.ReLinkerInstance.cleanupOldLibFiles(ReLinkerInstance.java:251)
            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:179)
            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
            at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$ReLinkerLibraryLoader.load(LibraryLoaderProviderImpl.java:38)
            at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
            at com.mapbox.mapboxsdk.maps.NativeMapView.<clinit>(NativeMapView.java:79)
            ... 11 more

com.mapbox.mapboxsdk.maps.AnnotationManagerTest > checksAddMarkers FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.mapbox.mapboxsdk.maps.NativeMapView
        at sun.reflect.GeneratedSerializationConstructorAccessor43.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
        at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
        at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:19)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:185)
        at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:69)
        at org.mockito.Mockito.mock(Mockito.java:1896)
        at org.mockito.Mockito.mock(Mockito.java:1805)
        at com.mapbox.mapboxsdk.maps.AnnotationManagerTest.checksAddMarkers(AnnotationManagerTest.java:52)
```

/cc @mapbox/maps-android

**Comment by friedbunny** [comment]
Eh, actually, I don’t think this is limited to any particular test, as [this job](https://circleci.com/gh/mapbox/mapbox-gl-native/235012) had 25 different tests fail.

**Comment by LukasPaczos** [comment]
Looks like this is caused by https://github.com/mapbox/mapbox-gl-native/pull/13974. Working on the fix.
