### PR TITLE
Install GeoJSONVT 2.1.6 from mason

### LINKED ISSUE #2226: update GeoJSON VT version
We should wait until after the next [`ios-v2.1.0`](https://github.com/mapbox/mapbox-gl-native/milestones/ios-v2.1.0) release for this, but per https://github.com/mapbox/mapbox-gl-native/commit/244fe93f0e6610cd7d66e1f9fd08ca84cb0dd7b2#commitcomment-13003393, we have a ton of work by @kkaefer on the C++ GeoJSON VT port in https://github.com/mapbox/geojson-vt-cpp/compare/995ffc72c556da4b4880a6036fbcf7159fc5ecce...master that has never made its way into production code here in GL, nor back to the JS port source. 

/cc @mourner

### PR DESCRIPTION
**Pull request by mikemorris**
Fixes #2226, #898 

- Defines `cxx_host` gyp variable to set `-fabi-version=0` on non-clang builds, fixes https://github.com/mapbox/mapbox-gl-native/issues/2502
- Sets `'GCC_SYMBOLS_PRIVATE_EXTERN': 'YES'` to prevent linker warnings on OS X builds using mason binaries built with [`-fvisibility-inlines-hidden=hidden`](https://github.com/mapbox/mason/blob/8a63d5a84f41c6686f0c7fd1ce49babff91df1bc/mason.sh#L56) or [`'GCC_SYMBOLS_PRIVATE_EXTERN': 'YES'`](https://github.com/mapbox/geojson-vt-cpp/blob/visibility-hidden/deps/common.gypi#L26)
- Links `libgeojsonvt.a` in `test/ios/ios-tests.xcodeproj` to fix an undefined symbol (unused in `libmbgl-core.a`) when linking iOS tests.
- Sets `Inline Methods Hidden` in `test/ios/ios-tests.xcodeproj` to fix linker warnings.

**TODO**:
- [ ] ~~https://github.com/mapbox/mapbox-gl-native/pull/2582 should be merged first for `gcc-5`, necessary for compatibility with mason libraries build with `clang-3.5` (https://github.com/mapbox/mapbox-gl-native/issues/2502)~~
- [x] Pull request and merge geojson-vt-cpp branch [`visibility-hidden`](https://github.com/mapbox/geojson-vt-cpp/tree/visibility-hidden) and tag a new release (v2.1.6.2).
- [x] Add a new mason package with the `-fvisibility=hidden` geojson-vt-cpp release
- [ ] After merging this, rebase https://github.com/mapbox/mapbox-gl-native/pull/2352, preserving @lucaswoj changes to build without a mason submodule

/cc @jfirebaugh @1ec5 @incanus @springmeyer

### CODE REVIEW

**Comment by mikemorris** [comment]
Travis iOS build is running to completion now, but still failing, looks like lots of linker warnings from symbol visibility issues still =(

**Comment by mikemorris** [comment]
I'm hitting a problem with MBGL mason-installed RapidJSON 1.0.2 causing symbol visibility linker warnings when building the iOS tests, which causes the Travis build to fail even though the tests compile, run and complete successfully.

[GeoJSONVT depends on mason-installed RapidJSON 1.0.2](https://github.com/mapbox/geojson-vt-cpp/blob/v2.1.6/configure#L46-L48) and I wonder if duplicate copies of these headers could be a problem? Reverting 2066295e358159ece5aa5717ad75567d0991a2b6 seems to resolve this for now, maybe we should revisit RapidJSON as a mason module at a later point.

/cc @jfirebaugh @1ec5

**Comment by jfirebaugh** [comment]
I get link errors building osxapp in Xcode, starting with:

```
duplicate symbol __ZN6mapbox4util9geojsonvt9GeoJSONVT7getTileEhjj in:
    /Users/john/Library/Developer/Xcode/DerivedData/osx-bcewhggtbhhvglavjnxcctvozqgg/Build/Products/Debug/libmbgl-core.a(geojsonvt.o)
    /Users/john/Development/mapbox-gl-native/mason_packages/osx-10.11/geojsonvt/2.1.6/lib/libgeojsonvt.a(geojsonvt.o)
```

**Comment by jfirebaugh** [comment]
Oh, stale submodule leftovers, disregard.

**Comment by mikemorris** [comment]
From https://github.com/herzbube/littlego/issues/3#issuecomment-11174752 and https://stackoverflow.com/questions/1601900/dont-expose-symbols-from-a-used-library-in-own-static-library it sounds like XCode does all sorts of screwy uncontrollable things when compiling and linking. I'm completely frustrated with trying to get this to work. Current work in https://github.com/mapbox/mapbox-gl-native/compare/geojsonvt-2.1.6-rapidjson, could really use some insight from @1ec5 or @incanus into XCode build settings here.

**Comment by 1ec5** [comment]
After merging geojsonvt-2.1.6-rapidjson with master locally, I also get this linker error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MGLPointAnnotation", referenced from:
      objc-class-ref in MapViewTests.o
```

**Comment by mikemorris** [comment]
@1ec5 That linker error should just be a simple fix with `MBGL_PUBLIC` prefix on class declaration like https://github.com/mapbox/mapbox-gl-native/commit/ce074bce693ec2247e9cafc381681fae562a3eae

**Comment by 1ec5** [comment]
> curious why I didn't see it though

The use of MGLPointAnnotation is new (introduced in #2612).

**Comment by mikemorris** [comment]
Added `MBGL_PUBLIC` to `MGLPointAnnotation` upstream in [`898-visibility-hidden`](https://github.com/mapbox/mapbox-gl-native/tree/898-visibility-hidden) and rebased @1ec5.

**Comment by mikemorris** [comment]
Pushed up a version that preserves the RapidJSON mason package, uses a new geojson-vt-cpp branch that sets `-fvisibility=hidden`, and sets `-fvisibility=hidden` in MBGL core to avoid differing visibility linker errors. This is building with no linker errors for me locally now.

/cc @jfirebaugh @1ec5 @tmpsantos for review

**Comment by mikemorris** [comment]
Bitrise iOS tests are failing because of a known issue (tracked in https://github.com/mapbox/mapbox-gl-native/pull/2769), but are compiling and linking successfully.

**Comment by lucaswoj** [comment]
anigif_enhanced-buzz-9066-1362757507-5

**Comment by incanus** [comment]
We don't do iOS on Travis anymore as of https://github.com/mapbox/mapbox-gl-native/commit/a243f41cb4807aa3784e2133986bda270464517c, just Bitrise. Also, just closed/merged https://github.com/mapbox/mapbox-gl-native/pull/2769 today.

**Comment by mikemorris** [comment]
Current Travis test failures being tracked in https://github.com/mapbox/mapbox-gl-native/issues/2819

**Comment by 1ec5** [comment]
No good: if I let CocoaPods wrap libMapbox.a in a dynamic library and link an application against that library, I get the following linker errors:

```
Undefined symbols for architecture x86_64:
  "mapbox::util::geojsonvt::Convert::create(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, mapbox::util::geojsonvt::ProjectedFeatureType, mapbox::util::variant<mapbox::util::geojsonvt::ProjectedPoint, mapbox::util::geojsonvt::ProjectedGeometryContainer>)", referenced from:
      mbgl::ShapeAnnotationImpl::updateTile(mbgl::TileID const&, mbgl::AnnotationTile&) in libMapbox.a(shape_annotation_impl.o)
  "mapbox::util::geojsonvt::Convert::project(std::__1::vector<mapbox::util::geojsonvt::LonLat, std::__1::allocator<mapbox::util::geojsonvt::LonLat> > const&, double)", referenced from:
      mbgl::ShapeAnnotationImpl::updateTile(mbgl::TileID const&, mbgl::AnnotationTile&) in libMapbox.a(shape_annotation_impl.o)
  "mapbox::util::geojsonvt::GeoJSONVT::getTile(unsigned char, unsigned int, unsigned int)", referenced from:
      mbgl::ShapeAnnotationImpl::updateTile(mbgl::TileID const&, mbgl::AnnotationTile&) in libMapbox.a(shape_annotation_impl.o)
  "mapbox::util::geojsonvt::GeoJSONVT::GeoJSONVT(std::__1::vector<mapbox::util::geojsonvt::ProjectedFeature, std::__1::allocator<mapbox::util::geojsonvt::ProjectedFeature> >, unsigned char, unsigned char, unsigned int, bool, double)", referenced from:
      mbgl::ShapeAnnotationImpl::updateTile(mbgl::TileID const&, mbgl::AnnotationTile&) in libMapbox.a(shape_annotation_impl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by incanus** [comment]
Dumb, obvious statement: `x86_64` refers to the iOS simulator slice (one of two, usually, the other being `i386` 32-bit) that needs to be built for local simulation. Is `GeoJSONVT` being built for that slice?

**Comment by jfirebaugh** [comment]
@1ec5 Is that something we could/should be testing in CI?

**Comment by 1ec5** [comment]
@jfirebaugh: We could introduce a dependency on CocoaPods in ios-test and copy in the `make ipackage` build output, but then we might as well implement #828.

**Comment by mikemorris** [comment]
This should be an easy fix - is that the full list of missing symbols @1ec5? `GeoJSONVT` is being built for that slice fine, but the symbols are hidden now and will need to be explicitly exposed with `__attribute__ ((visibility ("default")))` @incanus

**Comment by 1ec5** [comment]
I get the same errors after setting `GEOJSONVT_VERSION=visibility-default` in scripts/ios/configure.sh, `distclean`ing, and dropping the library into an existing pod.

**Comment by mikemorris** [comment]
Welp, those symbols are definitely missing @1ec5.
```
                 (undefined) external __ZN6mapbox4util9geojsonvt7Convert6createENSt3__13mapINS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEESA_NS3_4lessISA_EENS8_INS3_4pairIKSA_SA_EEEEEENS1_20ProjectedFeatureTypeENS0_7variantIJNS1_14ProjectedPointENS1_26ProjectedGeometryContainerEEEE
                 (undefined) external __ZN6mapbox4util9geojsonvt7Convert7projectERKNSt3__16vectorINS1_6LonLatENS3_9allocatorIS5_EEEEd
                 (undefined) external __ZN6mapbox4util9geojsonvt9GeoJSONVT7getTileEhjj
                 (undefined) external __ZN6mapbox4util9geojsonvt9GeoJSONVTC1ENSt3__16vectorINS1_16ProjectedFeatureENS3_9allocatorIS5_EEEEhhjbd
```

**Comment by springmeyer** [comment]
> Welp, those symbols are definitely missing @1ec5. Not sure why yet.

If this is not solvable through visibility fixes, it may be that the linker is intentionally removing the symbols because they appear unused. Something to try then would be to ask the linker to create `libMapbox.a` with all symbols, even those that look unused by passing `-Wl,--whole-archive`

**Comment by ljbade** [comment]
I tested this branch on my Android Samsung and did not have any problems.

**Comment by mikemorris** [comment]
Yea, that's kinda my current line of thinking @springmeyer, that they appear unused because they're defined in `libmbgl-core.a` but only used in `platform-ios.a`. I think the multiple tiers of compilation units/linking is definitely making this more complex - I had tried adding `-Wl,--whole-archive` around `geojsonvt_static_libs` yesterday but I'm assuming I implemented it wrong since it didn't seem to have an effect.

**Comment by mikemorris** [comment]
Still seeing 199 variations of the following (apparently spurious) linker warning in Xcode when copying `libMapbox.a` into a CocoaPods project (created following the instructions at https://www.mapbox.com/ios-sdk), but no more errors and I'm able to successfully build and make a map show up now! (Following https://www.mapbox.com/guides/first-steps-ios-sdk/)

```
warning: (x86_64) /Users/mikemorris/Dropbox (Mapbox)/Projects/CocoaPods/Pods/Mapbox-iOS-SDK/libMapbox.a(libuv_la-fs-poll.o) unable to open object file: No such file or directory
```

Can you try this out @1ec5 @springmeyer?

**Comment by mikemorris** [comment]
Okay, pushed up a new build that only sets `-fvsibility-inlines-hidden` instead of `-fvisibility=hidden` and drops the `__attribute__ ((visibility ("default")))` stuff from the iOS public API. We can try moving fully to `-fvisibility=hidden` later but I think this is all working as is now...
