### ISSUE TITLE
Build with GCC 13.1.1 fails with `geometry.hpp:9:24: error: found ‘:’ in nested-name-specifier, expected ‘::’`  and subsequent errors `error: ‘FeatureType’ has not been declared`.

### ISSUE THREAD

**Issue by dreirund** [mapbox/mapbox-gl-native#16672]
When I compile (with GCC 13.1.1), build fails with  
`geometry.hpp:9:24: error: found ‘:’ in nested-name-specifier, expected ‘::’`  
and subsequent errors `error: ‘FeatureType’ has not been declared`.

I have run:

Complete `cmake` call:

```bash
cmake \
  -DBUILD_TESTING=OFF\
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX='/usr' \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DMBGL_WITH_CORE_ONLY=OFF \
  -DMBGL_WITH_COVERAGE=OFF \
  -DMBGL_WITH_OPENGL=ON \
  -DMBGL_WITH_QT=OFF \
  -DMBGL_WITH_RTTI=ON \
  -DMBGL_WITH_SANITIZER=OFF \
  -DMBGL_WITH_WERROR=OFF \
  .
make -j1
```

Complete `make -j1` output:

```make
[  0%] Building C object CMakeFiles/mbgl-vendor-sqlite.dir/vendor/sqlite/src/sqlite3.c.o
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/vendor/sqlite/src/sqlite3.c: In function ‘sqlite3SelectNew’:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/vendor/sqlite/src/sqlite3.c:121468:10: warning: function may return address of local variable [-Wreturn-local-addr]
121468 |   return pNew;
       |          ^~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/vendor/sqlite/src/sqlite3.c:121430:10: note: declared here
121430 |   Select standin;
       |          ^~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/vendor/sqlite/src/sqlite3.c:121430:10: note: declared here
[  1%] Linking C static library libmbgl-vendor-sqlite.a
[  1%] Built target mbgl-vendor-sqlite
[  1%] Building CXX object CMakeFiles/mbgl-vendor-csscolorparser.dir/vendor/csscolorparser/csscolorparser.cpp.o
[  1%] Linking CXX static library libmbgl-vendor-csscolorparser.a
[  1%] Built target mbgl-vendor-csscolorparser
[  1%] Building CXX object CMakeFiles/mbgl-vendor-parsedate.dir/vendor/parsedate/parsedate.cpp.o
[  1%] Linking CXX static library libmbgl-vendor-parsedate.a
[  1%] Built target mbgl-vendor-parsedate
[  2%] Building C object CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/ducet.c.o
[  2%] Building C object CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/strcoll.c.o
[  2%] Building C object CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/strings.c.o
[  2%] Building C object CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/tolower.c.o
[  2%] Building C object CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/tounaccent.c.o
[  2%] Building C object CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/toupper.c.o
[  3%] Building C object CMakeFiles/mbgl-vendor-nunicode.dir/vendor/nunicode/src/libnu/utf8.c.o
[  3%] Linking C static library libmbgl-vendor-nunicode.a
[  3%] Built target mbgl-vendor-nunicode
[  4%] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/actor/mailbox.cpp.o
[  4%] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/actor/scheduler.cpp.o
[  4%] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_manager.cpp.o
In file included from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/annotation/annotation.hpp:3,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/annotation/annotation_manager.hpp:3,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/annotation/annotation_manager.cpp:1:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:9:6: warning: elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword
    9 | enum class FeatureType : uint8_t {
      | ~~~~ ^~~~~
      |      -----
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:9:24: error: found ‘:’ in nested-name-specifier, expected ‘::’
    9 | enum class FeatureType : uint8_t {
      |                        ^
      |                        ::
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:9:12: error: ‘FeatureType’ has not been declared
    9 | enum class FeatureType : uint8_t {
      |            ^~~~~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:9:34: error: expected unqualified-id before ‘{’ token
    9 | enum class FeatureType : uint8_t {
      |                                  ^
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:48:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   48 |     FeatureType operator()(const EmptyGeometry&) const { return FeatureType::Unknown; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:50:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   50 |     FeatureType operator()(const Point<T> &) const { return FeatureType::Point; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:52:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   52 |     FeatureType operator()(const MultiPoint<T> &) const { return FeatureType::Point; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:54:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   54 |     FeatureType operator()(const LineString<T> &) const { return FeatureType::LineString; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:56:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   56 |     FeatureType operator()(const MultiLineString<T> &) const { return FeatureType::LineString; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:58:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   58 |     FeatureType operator()(const Polygon<T> &) const { return FeatureType::Polygon; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:60:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   60 |     FeatureType operator()(const MultiPolygon<T> &) const { return FeatureType::Polygon; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:62:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   62 |     FeatureType operator()(const mapbox::geometry::geometry_collection<T> &) const { return FeatureType::Unknown; }
      |     ^~~~~~~~~~~
      |     ToFeatureType
In file included from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/feature.hpp:4,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/color.hpp:4,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/annotation/annotation.hpp:5:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:30:30: error: ‘std::string mbgl::util::toString’ redeclared as different kind of entity
   30 | std::string toString(uint64_t);
      |                              ^
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:29:13: note: previous declaration ‘std::string mbgl::util::toString(int64_t)’
   29 | std::string toString(int64_t);
      |             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:30:22: error: ‘uint64_t’ was not declared in this scope
   30 | std::string toString(uint64_t);
      |                      ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:5:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include <cstdlib>
  +++ |+#include <cstdint>
    5 | #include <type_traits>
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:32:30: error: ‘std::string mbgl::util::toString’ redeclared as different kind of entity
   32 | std::string toString(uint32_t);
      |                              ^
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:31:13: note: previous declaration ‘std::string mbgl::util::toString(int32_t)’
   31 | std::string toString(int32_t);
      |             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:32:22: error: ‘uint32_t’ was not declared in this scope
   32 | std::string toString(uint32_t);
      |                      ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:32:22: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:39:1: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’ [-Wc++17-extensions]
   39 | inline std::string toString(uint16_t t) {
      | ^~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:39:29: error: ‘std::string mbgl::util::toString’ redeclared as different kind of entity
   39 | inline std::string toString(uint16_t t) {
      |                             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:35:20: note: previous declaration ‘std::string mbgl::util::toString(int16_t)’
   35 | inline std::string toString(int16_t t) {
      |                    ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:39:29: error: ‘uint16_t’ was not declared in this scope
   39 | inline std::string toString(uint16_t t) {
      |                             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:39:29: note: ‘uint16_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:47:1: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’ [-Wc++17-extensions]
   47 | inline std::string toString(uint8_t t) {
      | ^~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:47:29: error: ‘std::string mbgl::util::toString’ redeclared as different kind of entity
   47 | inline std::string toString(uint8_t t) {
      |                             ^~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:43:20: note: previous declaration ‘std::string mbgl::util::toString(int8_t)’
   43 | inline std::string toString(int8_t t) {
      |                    ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:47:29: error: ‘uint8_t’ was not declared in this scope
   47 | inline std::string toString(uint8_t t) {
      |                             ^~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:47:29: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:51:51: error: ‘uint64_t’ was not declared in this scope
   51 | template <typename = std::enable_if<!std::is_same<uint64_t, unsigned long>::value>>
      |                                                   ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:51:51: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:51:74: error: template argument 1 is invalid
   51 | template <typename = std::enable_if<!std::is_same<uint64_t, unsigned long>::value>>
      |                                                                          ^
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:51:77: error: template argument 1 is invalid
   51 | template <typename = std::enable_if<!std::is_same<uint64_t, unsigned long>::value>>
      |                                                                             ^~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp: In function ‘std::string mbgl::util::toString(long unsigned int)’:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:53:33: error: ‘uint64_t’ does not name a type
   53 |     return toString(static_cast<uint64_t>(t));
      |                                 ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:53:33: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp: At global scope:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:56:51: error: ‘uint64_t’ was not declared in this scope
   56 | template <typename = std::enable_if<!std::is_same<uint64_t, unsigned long long>::value>>
      |                                                   ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:56:51: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:56:79: error: template argument 1 is invalid
   56 | template <typename = std::enable_if<!std::is_same<uint64_t, unsigned long long>::value>>
      |                                                                               ^
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:56:82: error: template argument 1 is invalid
   56 | template <typename = std::enable_if<!std::is_same<uint64_t, unsigned long long>::value>>
      |                                                                                  ^~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp: In function ‘std::string mbgl::util::toString(long long unsigned int)’:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:58:33: error: ‘uint64_t’ does not name a type
   58 |     return toString(static_cast<uint64_t>(t));
      |                                 ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:58:33: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp: At global scope:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:74:19: error: ‘uint32_t’ was not declared in this scope
   74 | std::string toHex(uint32_t);
      |                   ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:74:19: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:75:13: error: redefinition of ‘std::string mbgl::util::toHex’
   75 | std::string toHex(uint64_t);
      |             ^~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:74:13: note: ‘std::string mbgl::util::toHex’ previously declared here
   74 | std::string toHex(uint32_t);
      |             ^~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:75:19: error: ‘uint64_t’ was not declared in this scope
   75 | std::string toHex(uint64_t);
      |                   ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:75:19: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/feature.hpp: In lambda function:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/feature.hpp:47:102: error: use of deleted function ‘std::string mbgl::util::toString(T) [with T = long unsigned int; std::string = std::__cxx11::basic_string<char>]’
   47 |         [](const std::string& value_) { return value_; }, [](uint64_t value_) { return util::toString(value_); },
      |                                                                                        ~~~~~~~~~~~~~~^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:72:13: note: declared here
   72 | std::string toString(T) = delete;
      |             ^~~~~~~~
In file included from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp:5,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/expression.hpp:3,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/property_expression.hpp:3,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/property_value.hpp:5,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/annotation/annotation.hpp:6:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/type.hpp: In member function ‘std::string mbgl::style::expression::type::Array::getName() const’:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/type.hpp:115:73: error: use of deleted function ‘std::string mbgl::util::toString(T) [with T = long unsigned int; std::string = std::__cxx11::basic_string<char>]’
  115 |             return "array<" + toString(itemType) + ", " + util::toString(*N) + ">";
      |                                                           ~~~~~~~~~~~~~~^~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:72:13: note: declared here
   72 | std::string toString(T) = delete;
      |             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp: In member function ‘void mbgl::style::expression::ParsingContext::error(std::string, std::size_t)’:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp:135:74: error: use of deleted function ‘std::string mbgl::util::toString(T) [with T = long unsigned int; std::string = std::__cxx11::basic_string<char>]’
  135 |         errors->push_back({std::move(message), key + "[" + util::toString(child) + "]"});
      |                                                            ~~~~~~~~~~~~~~^~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:72:13: note: declared here
   72 | std::string toString(T) = delete;
      |             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp:135:26: error: no matching function for call to ‘std::vector<mbgl::style::expression::ParsingError>::push_back(<brace-enclosed initializer list>)’
  135 |         errors->push_back({std::move(message), key + "[" + util::toString(child) + "]"});
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/13.1.1/vector:66,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/vendor/mapbox-base/deps/geometry.hpp/include/mapbox/geometry/line_string.hpp:6,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/vendor/mapbox-base/deps/geometry.hpp/include/mapbox/geometry/geometry.hpp:5,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/geometry.hpp:3:
/usr/include/c++/13.1.1/bits/stl_vector.h:1278:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = mbgl::style::expression::ParsingError; _Alloc = std::allocator<mbgl::style::expression::ParsingError>; value_type = mbgl::style::expression::ParsingError]’
 1278 |       push_back(const value_type& __x)
      |       ^~~~~~~~~
/usr/include/c++/13.1.1/bits/stl_vector.h:1278:35: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<mbgl::style::expression::ParsingError>::value_type&’ {aka ‘const mbgl::style::expression::ParsingError&’}
 1278 |       push_back(const value_type& __x)
      |                 ~~~~~~~~~~~~~~~~~~^~~
/usr/include/c++/13.1.1/bits/stl_vector.h:1295:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(value_type&&) [with _Tp = mbgl::style::expression::ParsingError; _Alloc = std::allocator<mbgl::style::expression::ParsingError>; value_type = mbgl::style::expression::ParsingError]’
 1295 |       push_back(value_type&& __x)
      |       ^~~~~~~~~
/usr/include/c++/13.1.1/bits/stl_vector.h:1295:30: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<mbgl::style::expression::ParsingError>::value_type&&’ {aka ‘mbgl::style::expression::ParsingError&&’}
 1295 |       push_back(value_type&& __x)
      |                 ~~~~~~~~~~~~~^~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp: In member function ‘void mbgl::style::expression::ParsingContext::error(std::string, std::size_t, std::size_t)’:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp:140:60: error: use of deleted function ‘std::string mbgl::util::toString(T) [with T = long unsigned int; std::string = std::__cxx11::basic_string<char>]’
  140 |             {std::move(message), key + "[" + util::toString(child) + "][" + util::toString(grandchild) + "]"});
      |                                              ~~~~~~~~~~~~~~^~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:72:13: note: declared here
   72 | std::string toString(T) = delete;
      |             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp:140:91: error: use of deleted function ‘std::string mbgl::util::toString(T) [with T = long unsigned int; std::string = std::__cxx11::basic_string<char>]’
  140 |             {std::move(message), key + "[" + util::toString(child) + "][" + util::toString(grandchild) + "]"});
      |                                                                             ~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/util/string.hpp:72:13: note: declared here
   72 | std::string toString(T) = delete;
      |             ^~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/include/mbgl/style/expression/parsing_context.hpp:139:26: error: no matching function for call to ‘std::vector<mbgl::style::expression::ParsingError>::push_back(<brace-enclosed initializer list>)’
  139 |         errors->push_back(
      |         ~~~~~~~~~~~~~~~~~^
  140 |             {std::move(message), key + "[" + util::toString(child) + "][" + util::toString(grandchild) + "]"});
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/13.1.1/bits/stl_vector.h:1278:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = mbgl::style::expression::ParsingError; _Alloc = std::allocator<mbgl::style::expression::ParsingError>; value_type = mbgl::style::expression::ParsingError]’
 1278 |       push_back(const value_type& __x)
      |       ^~~~~~~~~
/usr/include/c++/13.1.1/bits/stl_vector.h:1278:35: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<mbgl::style::expression::ParsingError>::value_type&’ {aka ‘const mbgl::style::expression::ParsingError&’}
 1278 |       push_back(const value_type& __x)
      |                 ~~~~~~~~~~~~~~~~~~^~~
/usr/include/c++/13.1.1/bits/stl_vector.h:1295:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(value_type&&) [with _Tp = mbgl::style::expression::ParsingError; _Alloc = std::allocator<mbgl::style::expression::ParsingError>; value_type = mbgl::style::expression::ParsingError]’
 1295 |       push_back(value_type&& __x)
      |       ^~~~~~~~~
/usr/include/c++/13.1.1/bits/stl_vector.h:1295:30: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<mbgl::style::expression::ParsingError>::value_type&&’ {aka ‘mbgl::style::expression::ParsingError&&’}
 1295 |       push_back(value_type&& __x)
      |                 ~~~~~~~~~~~~~^~~
In file included from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/geometry/feature_index.hpp:4,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/tile/geometry_tile.hpp:4,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/annotation/annotation_tile.hpp:4,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/annotation/annotation_manager.cpp:3:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/tile/geometry_tile_data.hpp: At global scope:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/tile/geometry_tile_data.hpp:50:13: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   50 |     virtual FeatureType getType() const = 0;
      |             ^~~~~~~~~~~
      |             ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/annotation/annotation_tile.hpp:28:5: error: ‘FeatureType’ does not name a type; did you mean ‘ToFeatureType’?
   28 |     FeatureType getType() const override;
      |     ^~~~~~~~~~~
      |     ToFeatureType
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/annotation/annotation_tile.hpp:48:21: error: ‘FeatureType’ has not been declared
   48 |                     FeatureType,
      |                     ^~~~~~~~~~~
In file included from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/properties.hpp:4,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/paint_property.hpp:4,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/layers/symbol_layer_properties.hpp:11,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/layers/symbol_layer_impl.hpp:5,
                 from /home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/annotation/annotation_manager.cpp:11:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/conversion/stringify.hpp:116:32: error: ‘FeatureType’ has not been declared
  116 | void stringify(Writer& writer, FeatureType type) {
      |                                ^~~~~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/conversion/stringify.hpp: In function ‘void mbgl::style::conversion::stringify(Writer&, int)’:
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/conversion/stringify.hpp:118:10: error: ‘FeatureType’ has not been declared
  118 |     case FeatureType::Unknown:
      |          ^~~~~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/conversion/stringify.hpp:121:10: error: ‘FeatureType’ has not been declared
  121 |     case FeatureType::Point:
      |          ^~~~~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/conversion/stringify.hpp:124:10: error: ‘FeatureType’ has not been declared
  124 |     case FeatureType::LineString:
      |          ^~~~~~~~~~~
/home/[...]/.cache/yay/mapbox-gl-native-git/src/mapbox-gl-native/src/mbgl/style/conversion/stringify.hpp:127:10: error: ‘FeatureType’ has not been declared
  127 |     case FeatureType::Polygon:
      |          ^~~~~~~~~~~
make[2]: *** [CMakeFiles/mbgl-core.dir/build.make:104: CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:301: CMakeFiles/mbgl-core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Platform:** Artix GNU/Linux (rolling release), gcc version: 13.1.1, cmake version: 3.26.4.  
**Mapbox SDK version:** `git describe --tags` shows `maps-v1.6.0-18-gf9b8ddb804`.

Regards!
