### ISSUE TITLE
Update OkHttp to 3.3.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5131]
A new version of the OkHttp dependency was released. 
More information about this in related [changelog](https://github.com/square/okhttp/blob/master/CHANGELOG.md).

**Comment by alashow** [comment]
@tobrun @bleege On 4.1.0-beta.1 I get following exception:
```ruby
FATAL EXCEPTION: OkHttp Dispatcher
     Process: tm.asmanoky.aziada, PID: 17919
     java.lang.NoSuchMethodError: No virtual method log(Ljava/lang/String;)V in class Lokhttp3/internal/Platform; or its super classes (declaration of 'okhttp3.internal.Platform' appears in /data/app/tm.asmanoky.aziada-2/base.apk)
         at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:109)
         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:157)
         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
         at okhttp3.RealCall.access$100(RealCall.java:30)
         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
         at java.lang.Thread.run(Thread.java:818)
```

My okhttp version was 3.2.0. Then I changed it to 3.3.0, 3.3.1, no result.

I get this exception only when I upgrade mapbox to 4.1.0-beta.1. Any ideas why?

Thank you.

**Comment by alashow** [comment]
Sorry, my bad. Forget to upgrade "okhttp3:logging-interceptor" to the same version.

**Comment by bleege** [comment]
@alashow Glad it's working again for you!

**Comment by josias-soares** [comment]
This work:
https://scholar.live/question/error-while-integrating-paypal-in-android
