### PR TITLE
[android Upgrade to latest jni.hpp

### LINKED ISSUE #9688: Attempt to remove non-JNI local reference, dumping thread
We have been hearing complaints about the following log message:

> Attempt to remove non-JNI local reference, dumping thread

Capturing from a Chromium issue:

> Whenever the parameters passed from Java to a JNI method (i.e. the incoming jobject parameters) are wrapped in a ScopedLocalJavaRef, this causes them to be deleted once they go out of scope with `JNIEnv::DeleteLocalRef`. On recent versions of ART with CheckJNI turned on, this causes a spammy warning to be printed to logcat stating `"Attempt to remove non-JNI local reference, dumping thread"` with a thread dump, as apparently parameters are not supposed to be deleted, only objects returned as local references from native->java JNI calls. **This is not actually a problem since the runtime just does nothing in this case (other than printing the warning)**

Discussion and related commits can be found in [chromium/506850](https://bugs.chromium.org/p/chromium/issues/detail?id=506850).

### LINKED ISSUE #11510: Cleanup JNI of java.lang.*
On the JNI side we have multiple files responsible for the definitions of java.lang.* classes:
 - https://github.com/mapbox/mapbox-gl-native/blob/release-boba/platform/android/src/java_types.hpp
 - https://github.com/mapbox/mapbox-gl-native/blob/release-boba/platform/android/src/java/lang.hpp

cc @ivovandongen

### LINKED ISSUE #11556: JNI Error weak global reference table overflow when animating
I'm using a slightly modified version of [https://github.com/mapbox/mapbox-gl-native/blob/dfb9b26e675a152a925fcc5b84c3e14b8b9779d2/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedSymbolLayerActivity.java#L265-L278](url) on a Huawei BTV-W09.  The main modification is that in the addRandomCars() method, I add 150 cars instead of 10.

### Background
In our app, we're currently using version 4.1.1 of the Mapbox SDK.  We want to upgrade to a more recent version, but need to switch away from using MarkerView if we do so.  We have modified code that is doing much of what we want with 5.5.1 and 6.0.0-beta.5 in terms of drawing moving items on the map using SymbolLayer.  However, since it crashes, we can't use either of these releases unless there is something else that we can do to avoid this problem.  

**Platform:** Android
**Mapbox SDK version:** 5.5.1, 6.0.0-beta.5 (both were tested)

### Steps to trigger behavior

 1. Open the app
 2. Observe it crash after several minutes

### Expected behavior

The app continues to run until stopped, and the symbols keep moving and rotating.

### Actual behavior

The app crashes after a few minutes, with the following error:

```
03-29 11:22:01.809 11482-11531/com.mapboxtest A/art: art/runtime/indirect_reference_table.cc:125] JNI ERROR (app bug): weak global reference table overflow (max=51200)
    art/runtime/indirect_reference_table.cc:125] weak global reference table dump:
    art/runtime/indirect_reference_table.cc:125]   Last 10 entries (of 51200):
    art/runtime/indirect_reference_table.cc:125]     51199: 0x12ec0520 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51198: 0x12ec04c0 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51197: 0x12ec0460 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51196: 0x12ec0400 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51195: 0x12ec03a0 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51194: 0x12ec0340 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51193: 0x12ec02e0 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51192: 0x12ec0280 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51191: 0x12ec0220 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]     51190: 0x12ec01c0 java.lang.Thread
    art/runtime/indirect_reference_table.cc:125]   Summary:
    art/runtime/indirect_reference_table.cc:125]         1 of com.mapbox.mapboxsdk.maps.NativeMapView
    art/runtime/indirect_reference_table.cc:125]         1 of android.opengl.GLSurfaceView$GLThread
    art/runtime/indirect_reference_table.cc:125]         1 of com.mapbox.mapboxsdk.maps.MapView$5
    art/runtime/indirect_reference_table.cc:125]      4961 of java.lang.Class (4961 unique instances)
    art/runtime/indirect_reference_table.cc:125]         1 of java.lang.ThreadGroup
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (1 elements)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (16 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (100 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         3 of byte[] (288 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:125]         3 of byte[] (576 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:125]         4 of byte[] (840 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:125]         6 of byte[] (1248 elements) (6 unique instances)
    art/runtime/indirect_reference_table.cc:125]         5 of byte[] (1296 elements) (5 unique instances)
    art/runtime/indirect_reference_table.cc:125]         3 of byte[] (1440 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:125]         8 of byte[] (1560 elements) (8 unique instances)
    art/runtime/indirect_reference_table.cc:125]         4 of byte[] (2304 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (3600 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         4 of byte[] (4320 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:125]         3 of byte[] (5016 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:125]         3 of byte[] (6912 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:125]         8 of byte[] (9216 elements) (8 unique instances)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (12672 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (15876 elements)
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (17280 elements)
    art/runtime/indirect_reference_table.cc:125]        29 of byte[] (20736 elements) (29 unique instances)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (21168 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]        16 of byte[] (25344 elements) (16 unique instances)
    art/runtime/indirect_reference_table.cc:125]        27 of byte[] (26244 elements) (27 unique instances)
    art/runtime/indirect_reference_table.cc:125]        50 of byte[] (29952 elements) (50 unique instances)
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (32256 elements)
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (32448 elements)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (34848 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         6 of byte[] (35344 elements) (6 unique instances)
    art/runtime/indirect_reference_table.cc:125]       128 of byte[] (36864 elements) (128 unique instances)
    art/runtime/indirect_reference_table.cc:125]         3 of byte[] (46656 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:125]         4 of byte[] (55296 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (58320 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (64260 elements)
    art/runtime/indirect_reference_table.cc:125]         4 of byte[] (73728 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:125]         4 of byte[] (76032 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (82368 elements)
    art/runtime/indirect_reference_table.cc:125]         6 of byte[] (82944 elements) (6 unique instances)
    art/runtime/indirect_reference_table.cc:125]         1 of byte[] (85264 elements)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (98136 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]        10 of byte[] (140160 elements) (10 unique instances)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (147456 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         2 of byte[] (207936 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:125]         8 of byte[] (349056 elements) (8 unique instances)
    art/runtime/indirect_reference_table.cc:125]       229 of java.lang.Thread (229 unique instances)
    art/runtime/indirect_reference_table.cc:125] 
    art/runtime/runtime.cc:368] Runtime aborting...
    art/runtime/runtime.cc:368] 
03-29 11:22:01.810 11482-11531/com.mapboxtest A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11531 (Thread-50561)
```

### PR DESCRIPTION
**Pull request by jfirebaugh**
Upgrade to jni.hpp 4.0.0-rc8. The main changes were:

* [Redo of ownership types](https://github.com/mapbox/jni.hpp/pull/30). Here, this mainly means replacing manual `jni::DeleteLocalRef` with use of `jni::Local<T>`/`jni::SeizeLocal`.
* Introduction of `jni::Class<T>::Singleton()`, replacing `jni::Class<T>::Find(env).NewGlobalRef(env).release()`. `jni::Class` is also no longer reassignable, so `Singleton` gets used heavily. One gotcha is that we still need to make sure it's called in the main thread during registration, because [`FindClass` will fail if run from a background thread](https://developer.android.com/training/articles/perf-jni#faq_FindClass).
* [Swapped argument order for `jni::Cast`.](https://github.com/mapbox/jni.hpp/commit/70e0e07dfb7a248bce65d558ce40e57669bd1ff0)

Binary size increases slightly, but I'm working on followups to gain this back.

I ran all the instrumented tests locally. Let me know if there are additional tests I should run.

Fixes #9688 -- we never attempt to delete a non-local reference
Fixes #11556 -- not using weak global references anymore
Fixes #11510

### CODE REVIEW

**Comment by ivovandongen** [comment]
@jfirebaugh I'm having some issues compiling this locally. Tried with ndk 16.1.4479499 and 17.1.4828580, but get the below error (for arm-v7 and v8a). Verified that master does compile.

```
FAILED: /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/arm64-v8a/launch-cxx /Users/ivo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=aarch64-none-linux-android --gcc-toolchain=/Users/ivo/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/ivo/Library/Android/sdk/ndk-bundle/sysroot  -DMBGL_USE_GLES2=1 -DRAPIDJSON_HAS_STDSTRING=1 -DUCHAR_TYPE=char16_t -D_GLIBCXX_USE_CXX11_ABI=0 -I../../../../../../../include -I../../../../../../../src -I../../../../../../../mason_packages/headers/geometry/0.9.3/include -I../../../../../../../mason_packages/headers/variant/1.1.4/include -I../../../../../../../mason_packages/headers/unique_resource/cba309e/include -I../../../../../../../mason_packages/headers/rapidjson/1.1.0/include -I../../../../../../../mason_packages/headers/boost/1.65.1/include -I../../../../../../../mason_packages/headers/geojson/0.4.2/include -I../../../../../../../mason_packages/headers/geojsonvt/6.6.0/include -I../../../../../../../mason_packages/headers/supercluster/0.2.2/include -I../../../../../../../mason_packages/headers/kdbush/0.1.1-1/include -I../../../../../../../mason_packages/headers/earcut/0.12.4/include -I../../../../../../../mason_packages/headers/protozero/1.5.2/include -I../../../../../../../mason_packages/headers/polylabel/1.0.3/include -I../../../../../../../mason_packages/headers/wagyu/0.4.3/include -I../../../../../../../mason_packages/headers/shelf-pack/2.1.1/include -I../../../../../../../mason_packages/headers/vector-tile/1.0.2/include -I../../../../../../default -I../../../../../ -I../../../../../../../mason_packages/headers/jni.hpp/4.0.0-rc8/include -I../../../../../../../mason_packages/android-arm-v8-21/icu/58.1-min-size/include -I../../../../../../../vendor/nunicode/include -I../../../../../../../vendor/expected/include -isystem /Users/ivo/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /Users/ivo/Library/Android/sdk/ndk-bundle/sources/android/support/include -isystem /Users/ivo/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/ivo/Library/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -Qunused-arguments -ftemplate-depth=1024 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wno-variadic-macros -Wno-unknown-pragmas -Werror -Wno-error=unknown-warning-option -Qunused-arguments -fcolor-diagnostics -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++14 -MD -MT CMakeFiles/mbgl-core.dir/platform/android/src/style/sources/custom_geometry_source.cpp.o -MF CMakeFiles/mbgl-core.dir/platform/android/src/style/sources/custom_geometry_source.cpp.o.d -o CMakeFiles/mbgl-core.dir/platform/android/src/style/sources/custom_geometry_source.cpp.o -c /Users/ivo/git/mapbox-gl-native/platform/android/src/style/sources/custom_geometry_source.cpp
  /Users/ivo/git/mapbox-gl-native/platform/android/src/style/sources/custom_geometry_source.cpp:114:74: error: expected '(' for function-style cast or type construction
          static auto isCancelled = javaClass.GetMethod<jboolean (jni::jint, jni::jint, jni::jint)>(*_env, "isCancelled");
                                                                  ~~~~~~~~~^
  /Users/ivo/git/mapbox-gl-native/platform/android/src/style/sources/custom_geometry_source.cpp:114:85: error: expected '(' for function-style cast or type construction
          static auto isCancelled = javaClass.GetMethod<jboolean (jni::jint, jni::jint, jni::jint)>(*_env, "isCancelled");
                                                                             ~~~~~~~~~^
  /Users/ivo/git/mapbox-gl-native/platform/android/src/style/sources/custom_geometry_source.cpp:114:96: error: expected '(' for function-style cast or type construction
          static auto isCancelled = javaClass.GetMethod<jboolean (jni::jint, jni::jint, jni::jint)>(*_env, "isCancelled");
                                                                                        ~~~~~~~~~^
  /Users/ivo/git/mapbox-gl-native/platform/android/src/style/sources/custom_geometry_source.cpp:114:35: error: use of undeclared identifier 'javaClass'
          static auto isCancelled = javaClass.GetMethod<jboolean (jni::jint, jni::jint, jni::jint)>(*_env, "isCancelled");
                                    ^
  /Users/ivo/git/mapbox-gl-native/platform/android/src/style/sources/custom_geometry_source.cpp:118:49: error: use of undeclared identifier 'javaClass'
          auto peer = jni::Cast(*_env, *javaPeer, javaClass);
                                                  ^
  5 errors generated.
  ninja: build stopped: subcommand failed.
```

**Comment by jfirebaugh** [comment]
I had just rebased the branch and there were some commits that conflicted. Try now.

**Comment by ivovandongen** [comment]
@jfirebaugh Above error is reproducible on a Galaxy Nexus  with Android 4.3. This device has the bare minimum for reference tables.

**Comment by jfirebaugh** [comment]
Thanks @ivovandongen, I'll take a look. Same repro steps as in #12762?

**Comment by jfirebaugh** [comment]
Looks like that overflow is caused by https://github.com/mapbox/mapbox-gl-native/commit/d297bf10ef89e97da30e1a00dd49560e18bcb3f0#diff-f0e8cf5a32c5a4047cdc6945b9fab894, rather than by these changes.

Given how easy it is to leak local refs, I think we should go ahead with https://github.com/mapbox/jni.hpp/issues/32. I'll look at doing this before the jni.hpp 4.0.0 final release.

**Comment by lekaha** [comment]
Hi, I got urgent might solved by this PR. Since it is already merged wondering when it will be released?

**Comment by kkaefer** [comment]
@lekaha This change will be part of the next release, which is tentatively scheduled for mid-October.
