### PR TITLE
Scale Instrumentation tests

### PR DESCRIPTION
**Pull request by tobrun**
WIP to cover a big part of our public API with instrumentation tests. This will help us start refactor work from https://github.com/mapbox/mapbox-gl-native/projects/4 without breaking the whole API. 

Initial focus:
- [x] moveCamera
- [x] easeCamera
- [x] AnimateCamera
- [x] setBearing
- [x] setPitch
- [x] setLatLng
- [x] CompassView
- [x] MyLocationView
- [x] MyLocationTracking/MyLocationBearing
- [x] Attribution
- [x] addMarker
- [x] addMarkerView
- [x] addPolygon
- [x] addPolyline
- [x] selectMarker (show infowindow)
- [x] CustomInfoWindowAdapter
- [x] ...

### CODE REVIEW

**Comment by tobrun** [comment]
@ivovandongen do you want to review?

**Comment by ivovandongen** [comment]
@tobrun Great stuff! I do get some failures though:

screen shot 2016-11-02 at 11 47 23

See [log output](https://gist.github.com/ivovandongen/3a06587efbc527399daf1ddc19f12b57)

**Comment by tobrun** [comment]
@ivovandongen thank you for testing, this was on a Nexus 5x?

**Comment by ivovandongen** [comment]
@tobrun Yes, sorry. It's my 5x with latests os updates.

**Comment by tobrun** [comment]
was able to reproduce with emulator, was missing some zoom deltas and moveBy was failing because the delta wasn't big enough for that type of test.

screen shot 2016-11-02 at 13 57 05

Going to do a final cleanup and squash the commits

**Comment by tobrun** [comment]
I resolved the merging conflicts, @ivovandongen want to review?

**Comment by ivovandongen** [comment]
@tobrun I'm getting some compile errors on a fresh checkout of this branch:

```
/Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/AttributionTest.java
Error:(53, 79) error: cannot find symbol variable attribution_names
Error:(54, 79) error: cannot find symbol variable attribution_links
Error:(77, 33) error: cannot find symbol variable attributionsDialogTitle
Error:(92, 33) error: cannot find symbol variable attributionsDialogTitle
Error:(106, 33) error: cannot find symbol variable attributionsDialogTitle
Error:(120, 33) error: cannot find symbol variable attributionsDialogTitle
Error:(124, 33) error: cannot find symbol variable attributionTelemetryTitle
/Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/MyLocationViewTest.java
Error:(82, 102) error: cannot find symbol variable ic_mylocationview_normal
Error:(84, 102) error: cannot find symbol variable ic_mylocationview_bearing
Error:Execution failed for task ':MapboxGLAndroidSDKTestApp:compileDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by tobrun** [comment]
those seems regressions from #6894, fixing up

**Comment by tobrun** [comment]
@ivovandongen fixed up the rebase issue with e3d78fe. 
Still wondering why CI didn't catch this issue because it should have flagged it.

**Comment by ivovandongen** [comment]
@tobrun One last failure in `MarkerTest#showInfoWindowTest`:

```

java.lang.IllegalStateException: MapView#onStart() was not called. You must call this method from the parent's {@link Activity#onStart()} or {@link Fragment#onStart()}.
at com.mapbox.mapboxsdk.maps.MapView.onResume(MapView.java:596)
at com.mapbox.mapboxsdk.testapp.activity.espresso.EspressoTestActivity.onResume(EspressoTestActivity.java:42)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnResume(MonitoringInstrumentation.java:564)
at android.app.Activity.performResume(Activity.java:6768)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
